### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by S-BLH**
1. made a repo
2. cloned it to my pc
3. created html,css and js files
4. added the linters
5. added the html,css and js codes
6. cleaned the code
7. added a design

### CODE REVIEW

**Review by ahzamir — CHANGES_REQUESTED** [review]
@S-BLH 

- You don't have your partner feedback on your project
- Your code does not work or show the Pokemon when I type their name in the input.
image

- Also your project does not have a README.md file
- And your codes does not passes the freecodecamp

**Comment by S-BLH** [comment]
@ahzamir Ostad as you said, I changes the whole project and added functionality to it. kindly, review it

**Comment by ahzamir** [comment]
@S-BLH 

- I can not see your partner feedback

**Comment by latifa-wakili** [comment]
your code didn't paased 2 freecodecamp errors

good design

**Comment by S-BLH** [comment]
@ahzamir, Ostad my partner's says that my code does not pass freecodecamp, but my code is functionaly right and passed the freecodecamp test, please review it

**Review by ahzamir — APPROVED** [review]
### Hi @S-BLH 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Pokemon Search App project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
